### ISSUE TITLE
Adding empty entities is broken

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/DEPRECATED-CWRC-Writer#123]

**Comment by ilovan** [comment]
Could you please clarify, @ajmacdonald ? Are you referring to the ability to add an entity at a certain location in text (all the tags and rdf) without selecting a string of text?

**Comment by ajmacdonald** [comment]
Yes. Trying to add an entity without first selecting any text. In the current version, attempting to do this is disabled.
