### ISSUE TITLE
Cursor is placed before "Note" in text

### ISSUE THREAD

**Issue by msellmer** [cwrc/DEPRECATED-CWRC-Writer#159]
When there is no text in front of the grey "note" tag, CWRC-Writer places the cursor in front of it (see image). Once you start writing in it, the text goes behind it, as expected. This happens in the mini CWRC-Writer when you add a note as well.

![screen shot 2014-05-27 at 2 51 45 pm](https://cloud.githubusercontent.com/assets/1838266/3098294/f2e88094-e5e9-11e3-8e08-e9bde8e2c614.png)

**Comment by ilovan** [comment]
Will close and open  more to the point issues arising from it.
