### ISSUE TITLE
Add "Copy tag and contents" to the right click options

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#171]

**Comment by ajmacdonald** [comment]
I've added it to the menu in the text area. Let me know if you'd also like it in the tree menu.

**Comment by ilovan** [comment]
Can't see it:
![screen shot 2015-10-14 at 2 09 08 pm](https://cloud.githubusercontent.com/assets/6600070/10496279/2e9f739c-727d-11e5-9024-1f8ee960867c.png)
Ideally, the option would be available in both text area and tree menu.

**Comment by ajmacdonald** [comment]
I don't see it either. I think the auto-build is not working.

**Comment by ilovan** [comment]
Thanks Andrew, 

Also, once the auto-build is working again, could you send me the link of the most recent commit to forward to dgi to use as a starting point for their development work?

Thanks,
Mihaela

**Comment by ajmacdonald** [comment]
@jchartrand can you have a look at the auto-build?

**Comment by ilovan** [comment]
Buttons have been added to both structure and text areas right-click menus, but are not functional in Git-Writer.

**Comment by ajmacdonald** [comment]
@ilovan I just tested this functionality in DevGitWriter and GitWriter and it works for me

**Comment by ilovan** [comment]
Checked again and you are right (I was just following the user documentation for the procedure and it needs to be updated). I will close this issue now.
