### ISSUE TITLE
Take CSS from declaration in template

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#215]
Need to move away from one-to-one correspondence between schema and css, and from fixed location for a single css associated with specific schema

nice enhancement for starting with a blank document:
selector in settings dialog box could allow user to switch between css for the same schemas

**Comment by ajmacdonald** [comment]
Partially implemented. Now checks for xml-stylesheet element when loading a document.

**Comment by SusanBrown** [comment]
Presumably waiting on the integration with Islandora to proceed further.

**Comment by ilovan** [comment]
I am assuming this issue is mitigated by the recent changes to the code requested by DGI.
Please correct me if I am wrong.

**Comment by ajmacdonald** [comment]
Document CSS is now prioritized over the schema CSS.

I think this issue can be closed unless a "selector in settings dialog box could allow user to switch between css for the same schemas" is still important.

**Comment by ilovan** [comment]
I think this is something we should consider for the platform-independent version of CWRC-Writer

**Comment by SusanBrown** [comment]
Let's consult with partner projects in the CANARIE grant about how important a setting for this is.

**Comment by jchartrand** [comment]
This sounds like something I might help with?  I'm not sure, though, which Canarie partners, and I'm not totally clear on the question.  Is it written up somewhere?

**Comment by jefferya** [comment]
Fyi. this change has the potential to impact the islandora_cwrc_writer and
islandora_cwrc_document modules used by the repository. Once the
CWRC-Writer is changed, affected parts of these repository modules may also
require changes.

**Comment by susanirenebrown** [comment]
This is not high priority for now: our focus is on changes for the launch. This is backburnered especially given the system implications.
