### ISSUE TITLE
Pop-up warning message when people try to copy and paste in CWRC Writer, with a link to the relevant section of the documentation

### ISSUE THREAD

**Issue by ilovan** [cwrc/DEPRECATED-CWRC-Writer#264]

**Comment by ajmacdonald** [comment]
The current messages are bit Clippy inspired. Please suggest alternative wording if necessary.

I haven't added a way to turn the messages off, but they also only show up the first time the relevant action is performed. Also, it looks like it could be fairly difficult to cancel a paste before it occurs so I haven't implemented that.

**Comment by ilovan** [comment]
Just for the record, I don't see this one either.
