### ISSUE TITLE
CWRC Writer initialization in Islandora - changes due to the integrated documentation in "validate" and "settings"

### ISSUE THREAD

**Issue by ilovan** [cwrc/DEPRECATED-CWRC-Writer#288]

**Comment by ilovan** [comment]
Jeff just updated CWRC Writer in the markup editor module installed on the cwrc dev site http://cwrc-dev-01.srv.ualberta.ca and the two localized help buttons you installed in the validation area and the settings pop-up. 

Error messages (Chrome dev tools):
![image](https://cloud.githubusercontent.com/assets/6600070/6178425/018ec5fe-b2cc-11e4-9b50-e687f349bcea.png)

**Comment by ajmacdonald** [comment]
Should work once the dev site's been update. Please confirm.

**Comment by jefferya** [comment]
@ilovan - update has been pulled down to the Islandora dev server.

**Comment by ilovan** [comment]
fixed
