### ISSUE TITLE
highlighting of tags inconsistent?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#307]
When I use the sample Russell letter and work down the markup tree into Opener then Dateline then Date, all the tags I click on in the left Markup panel highlight except for Date. Why?

**Comment by ajmacdonald** [comment]
It's highlighting the date entity. Entity highlights are currently show by a thickening of the dotted underline.

**Comment by SusanBrown** [comment]
It highlights the entire dateline in blue when I click on that tag name, but when I click on date in the markup panel there is no highlighting (thought it is underlined). Shouldn’t it highlight in blue like the other tags?

**Comment by ajmacdonald** [comment]
I can't recall why I originally treated the highlighting of tags and entities differently. This can certainly be changed however.

**Comment by SusanBrown** [comment]
Ah I see now, sorry for being dense about what you were saying. Yes, I think the entities should be highlighted like other tagged portions of texts, when the tags are selected in the markup panel. Obviously if there is no equivalent tag, e.g. as a result of using overlap mode, all that would happen is the dotted underlining.

**Comment by ilovan** [comment]
Same as https://github.com/cwrc/CWRC-WriterBase/issues/50. 
Will close current issue for now.
