### ISSUE TITLE
Add tag functionality to entity tags

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#316]
The lack of the right-click options for tags associated with entities limits what can be done from the markup panel. 
Insert tag Before/After/Inside
Change/Edit/Remove Tag should also be available, and ideally they should say "Change Tag/Entity" etc.

Edit/Copy Entity should remain available as well. 
I think it is best to keep them separate, at least for now, rather than combining them with the tag commands, to avoid confusion, even though there will be redundancy.

**Comment by ajmacdonald** [comment]
Added most of the functionality. Still needs testing and changes to how entity selection works from within the tree.

**Comment by SusanBrown** [comment]
@ilovan please test

**Comment by SusanBrown** [comment]
Seems fixed. Asking Cailin to do more extensive testing.
