### ISSUE TITLE
Links in entity panel

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#370]
{this is not for immediate action b/c we need to get the entity aggregation page working, but I'm raising it here in case it needs discussion/details worked out}

Clicking on the "ref" or URI in the expanded view of an entity should take you to:
- for cwrc uris: the Entity Aggregation page for that entity (cwrc will provide details, but it should just involve loading the URI as with any other URL)
- for external uris: the associated web page representation of that entity

**Comment by SusanBrown** [comment]
Colin and Cailin, please test this by adding an entity for E Pauline Johnson that links to the CWRC entity for her (the one with Tekhionwake (maybe misspelled here) in brackets in the name label.

**Comment by SusanBrown** [comment]
@cailinr I think this is working (though EAPs are loading very slowly still) -- please test

**Comment by cailinr** [comment]
Yes, seems to be working! Tested with http://beta.cwrc.ca/islandora/object/islandora%3A9a05c33c-0ce8-4898-ab52-565556594f84#islandora:9a05c33c-0ce8-4898-ab52-565556594f84 

There were 2 old PJ entities in the doc already (which brings you to a "page not found" page when clicking the refs) and the entity I added links to the PJ (Tekahionwake) EAP

@SusanBrown
