### ISSUE TITLE
read external schemas from any server.

### ISSUE THREAD

**Issue by ilovan** [cwrc/DEPRECATED-CWRC-Writer#386]
@jchartrand , could you please expand on the solution you considered the best option during our conversation on Friday?

**Comment by jchartrand** [comment]
On Friday we were talking about the ‘reference implementation’ or ‘sandbox’ version of the CWRC-Writer server, for which I’ll create an admin function (on an admin page) to ‘register' external schema URIs.  There will then be a proxy on the server that will fetch the corresponding schema (from the remote host) when needed.  The proxy will only fetch registered schemas.

I’m guessing, however, that’d you’d like something similar for the existing CWRC-Writer setup.  If so, you could build a proxy service like the one I’ll build for the sandbox, or you could simply continue to do what you’d been doing, add an apache reverse proxy entry (ProxyPass) for each external server whose schemas you’d like to support:

https://github.com/cwrc/CWRC-Writer/issues/190#issuecomment-48369946

**Comment by ilovan** [comment]
I know we talked briefly about this functionality earlier this spring and that when I load an EpiDoc document into GitWriter I get a schema loading error.

This is the EpiDoc I was talking about: https://github.com/ilovan/Test-EpiDoc-document-in-GitWriter

Is this problem I ran into caused by the solution described in the current issue never being implemented?

**Comment by ajmacdonald** [comment]
Yes. As far as I know a proxy for fetching schemas was never completed.

**Comment by jchartrand** [comment]
Here is the error when loading Mihaela's Test-EpiDoc-document-in-GitWriter document:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/547165/43529176-addaa656-9578-11e8-936e-4eeb3bf06c10.png">

No 'schema registry' was ever built.  I think we opted to just use reverse proxies.  So, I think the first thing to try is to have Jeff add a ProxyPass for the epidoc schema, that accepts an https request from the CWRC-Writer for the schema, goes out and gets the schema from the http url, and returns it to the CWRC-Writer.
