### ISSUE TITLE
Orlando entity handling: Place entity - Is there any reason why @annotationId is added to both PLACE and GEOG? when converting a tag to an entity?

### ISSUE THREAD

**Issue by ilovan** [cwrc/DEPRECATED-CWRC-Writer#388]
If yes, please specify ( @ajmacdonald ) and make the changes in the Orlando v2 schemas ( @brundin ).

If no, please fix (Andrew).

**Comment by ajmacdonald** [comment]
Yes, the reason is so that CWRC-Writer knows that the child tag is part of the information used to describe the entity. It's used when loading a document into the editor.

**Comment by ajmacdonald** [comment]
`annotationId` is no longer being used
