### ISSUE TITLE
Full-screen function

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#413]
Could we have a full-screen function? It wouldn't make a huge difference in the stand-alone but a big difference in the embedded one.

**Comment by ajmacdonald** [comment]
This is possible. I don't think the functionality would require much knowledge of the internals of CWRC-Writer so could be implemented by DE.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/ac2d7331982ec6a8257976192124b85bf5b1a147
