### ISSUE TITLE
Ctrl-F Search doesn't work within reading panel of CWRC-Reader

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#460]
@ajmacdonald I can't test this on the standalone because it doesn't include the reader. Can you determine whether this can/should be fixed on your end?

Searching within the editing panel works in both.

**Comment by ajmacdonald** [comment]
Read-only mode tries to block any keys inputted into the editing/reading pane. You can get search working but you have to shift focus (by clicking) outside of that pane, and then use ctrl+f.

**Comment by ilovan** [comment]
Confirmed in the old CWRC-Reader. Waiting for an integrated version of the new Reader to test; My guess is that this could be mitigated by a popup instructing the user to click outside the text area.

**Comment by ilovan** [comment]
Still an issue in the new integrated version

**Comment by ilovan** [comment]
@ajmacdonald , can we detect when the user wants to use the browser search and warn them whit a popup to click outside the text area?

**Comment by ajmacdonald** [comment]
3ae89a924199b39a34d367d0266885a1920c5867

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/3ae89a924199b39a34d367d0266885a1920c5867

**Comment by ilovan** [comment]
working now

**Comment by ilovan** [comment]
confirmed on prod cwrc
