### ISSUE TITLE
Selecting all in the Edit Source box

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#461]
When you open up the edit source box and hit Ctrl-A (select all) much of the rest of the screen selects, not the popup containing the source text. 

You have to click on the box and then use Ctrl-A. Not fatal, but annoying because it happens (to me) repeatedly.

![image](https://cloud.githubusercontent.com/assets/545952/20645261/712fcbb2-b426-11e6-8938-01a8bce7f45c.png)

Standalone CWRC-Writer
Chrome on a Mac

**Comment by ajmacdonald** [comment]
Please test.

**Comment by SusanBrown** [comment]
@cailinr pls test
