### ISSUE TITLE
clicking on tag doesn't always expand the elements in which it is nesting

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#466]
I clicked in the standalone sample Orlando bio doc on the bibcit icon right after 1898. It highlighted the correct paragraph but did not expand it to highlight the bibcit.

I find though that if you double click then it does expand.

![image](https://cloud.githubusercontent.com/assets/545952/20645631/fb3e90a8-b431-11e6-819a-d90718344c06.png)

**Comment by ajmacdonald** [comment]
@SusanBrown with the recent CSS changes to BIBCIT can you confirm if this is still an issue?
