### ISSUE TITLE
TEI schema mappings: change values of @ cert attribute 

### ISSUE THREAD

**Issue by ilovan** [cwrc/DEPRECATED-CWRC-Writer#485]
Current values: 
- definite
- reasonably certain
- probable
- speculative

Requested values:
- high
- low
- medium
- unknown

**Comment by ajmacdonald** [comment]
These values are in the [schema](https://cwrc.ca/schemas/cwrc_tei_lite.rng) and need to be changed there.

**Comment by ilovan** [comment]
Thanks, Andrew, I am aware of it. I think I accidentally moved this issue from the "reference" pipeline to "On deck".

**Comment by ilovan** [comment]
https://github.com/cwrc/CWRC-Schema/issues/125
