### ISSUE TITLE
rename templates to make them clearer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#489]
![image](https://user-images.githubusercontent.com/545952/34282652-3f981274-e695-11e7-8422-dff1a9e23e3f.png)

Can we please rename these as follows (similar to what we had in the former standalone interface)?
If it would be best to go with file names without spaces, then use the version in square brackets
writing.xml --> Orlando Writing document template [Orlando_writing_document_template.xml]
sample_writing.xml --> Sample Orlando Writing document [Sample_Orlando_Writing_document.xml]
sample_poem.xml--> Sample TEI poem [Sample_TEI_poem.xml]
sample_letter.xml--> Sample TEI letter [Sample_TEI_letter.xml]
sample_biography.xml --> Sample Orlando Biography document [Sample_Orlando_Biography_document.xml]
prose.xml--> TEI prose template [TEI_prose_template.xml]
poem.xml--> TEI poem template [TEI_poem_template.xml]
letter.xml--> TEI letter template [TEI_letter_template.xml]
[cwrcEntry.xml ---------> remove for now because it is not usable. See https://github.com/cwrc/CWRC-Writer/issues/494]
ceww_new_entry_template.xml--->CWRC Canada's Early Women Writers template [CWRC_Canada's_Early_Women_Writers template.xml
biography.xml---> Orlando Biography document template [Orlando_biography_document_template.xml]
Sample_Canadian_Women_Playwrights_entry.xml --> Sample CWRC Canadian Women Playwrights entry.xml [Sample_CWRC Canadian_Women_Playwrights_entry.xml]

Please reorder alphabetically once renamed.

**Comment by SusanBrown** [comment]
Not sure whether this would best be tackled by @ajmacdonald or @jchartrand. Added to priorities On Deck in project.

**Comment by jchartrand** [comment]
I can do this one.

**Comment by jchartrand** [comment]
Can I simply rename the files in the GitHub repository:

https://github.com/cwrc/CWRC-Writer-Templates/tree/master/templates

?

The templates that appear in the CWRC-Writer just pull from that repo.

**Comment by SusanBrown** [comment]
Yes go ahead.

**Comment by jchartrand** [comment]
I renamed writing.xml to 

```Orlando Writing document template.xml```

So with spaces in the name, but also with a .xml extension (which is a combination of the options that you proposed above).   It seems to work fine (at least in the GitWriter).  

Shall I rename all the others similarly?
